@server_url = http://127.0.0.1:3333
@name = 

@page_num = 2

GET {{server_url}} HTTP/1.1

###

GET {{server_url}}/web_devices HTTP/1.1

###
POST {{server_url}}/login HTTP/1.1
content-type: application/json

{
    "login": "",
    "password": "" 
}

###

GET {{server_url}}/organizations?login={{name}} HTTP/1.1

###
POST {{server_url}}/logout?login={{name}} HTTP/1.1

###
POST {{server_url}}/search?login={{name}} HTTP/1.1
content-type: application/json

{
    "search": "Петров",
    "school_id": 0,
    "deleted" : false
}

###
POST {{server_url}}/search_page?login={{name}}&page_number={{page_num}} HTTP/1.1