@server_url = http://127.0.0.1:3333
@login = {{$dotenv LOGIN}}
@pass = {{$dotenv PASSWORD}}

GET {{server_url}} HTTP/1.1

###

GET {{server_url}}/web_devices HTTP/1.1

###
POST {{server_url}}/login HTTP/1.1
content-type: application/json

{
    "login": "{{login}}",
    "password": "{{pass}}"
}

###

GET {{server_url}}/organizations?login={{login}} HTTP/1.1

###
POST {{server_url}}/logout?login={{login}} HTTP/1.1

###
POST {{server_url}}/search?login={{login}} HTTP/1.1
content-type: application/json

{
    //28706737
    "search": "",
    "org_id": 0,
    "show_deleted" : false
}

### //879
POST {{server_url}}/download_all?login={{login}} HTTP/1.1
content-type: application/json

{
    "org_id": 906, 
    "cards": 0,
    "show_deleted" : false
}

###
@page_num = 2
POST {{server_url}}/search_page?login={{login}}&page_number={{page_num}} HTTP/1.1

###
@num = 5
POST {{server_url}}/person_info?login={{login}}&num={{num}} HTTP/1.1