@server_url = http://127.0.0.1:3333
@name = 

GET {{server_url}} HTTP/1.1

###

GET {{server_url}}/web_devices HTTP/1.1

###
POST {{server_url}}/login HTTP/1.1
content-type: application/json

{
    "login": "",
    "password": "" 
}

###

GET {{server_url}}/organizations?login={{name}} HTTP/1.1

GET {{server_url}}/logout?login={{name}} HTTP/1.1