[package]
name = "card_crm_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "*"
sqlx = { version = "0.6", features = [
    "postgres",
    "macros",
    "runtime-tokio-rustls",
] }
dotenvy = "0.15.6"
