pub static LOGOUT: [(&str, &str); 5] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    ("headerForm", "headerForm"),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (
        "headerForm:j_id_jsp_659141934_66",
        "headerForm:j_id_jsp_659141934_66",
    ),
];

pub static CLICK_CLIENTS_LIST: [(&str, &str); 8] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "mainMenuSubView:mainMenuForm:mainMenuselectedItemName",
        "showClientListMenuItem",
    ),
    (
        "panelMenuStatemainMenuSubView:mainMenuForm:clientGroupMenu",
        "opened",
    ),
    (
        "panelMenuActionmainMenuSubView:mainMenuForm:showClientListMenuItem",
        "mainMenuSubView:mainMenuForm:showClientListMenuItem",
    ),
    (
        "mainMenuSubView:mainMenuForm",
        "mainMenuSubView:mainMenuForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (
        "mainMenuSubView:mainMenuForm:showClientListMenuItem",
        "mainMenuSubView:mainMenuForm:showClientListMenuItem",
    ),
];

pub static ORG_MODAL: [(&str, &str); 5] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "workspaceSubView:workspaceForm",
        "workspaceSubView:workspaceForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (OPEN_ORG_SEARCH_KEY, OPEN_ORG_SEARCH_KEY),
];

pub static CLICK_OPEN_ORG_POPUP: [(&str, &str); 6] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_24pc22",
        "1",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm",
        "orgSelectSubView:modalOrgSelectorForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_25pc22",
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_25pc22",
    ),
];

pub static CLICK_ORG_PAGE: [(&str, &str); 12] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_5pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_12pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_15pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_18pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_24pc22",
        "0",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm",
        "orgSelectSubView:modalOrgSelectorForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    ("ajaxSingle", CLICK_ORG_PAGE_KEY),
    (CLICK_ORG_PAGE_KEY, ""),
    ("AJAX:EVENTS_COUNT", "1"),
];

pub static SEARCH_FORM: [(&str, &str); 28] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_1pc51",
        "true",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_5pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_8pc51",
        "on",
    ),
    (SEARCH_ID_KEY, ""),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_14pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_16pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_18pc51",
        "-1",
    ),
    (LAST_NAME_KEY, ""),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_28pc51",
        "",
    ),
    (NAME_KEY, ""),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_32pc51",
        "",
    ),
    (SURNAME_KEY, ""),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_38pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_40pc51",
        "",
    ),
    (CARDS_KEY, "0"),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_46pc51",
        "0",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_49pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_51pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_51pc51",
        "",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_108pc51",
        "j_id_jsp_635818149_109pc51",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_112pc51",
        "0,00",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_126pc51",
        "0,00",
    ),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:removedClientDeletePanelOpenedState",
        "",
    ),
    (
        "workspaceSubView:workspaceForm",
        "workspaceSubView:workspaceForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (SUBMIT_SEARCH_KEY, SUBMIT_SEARCH_KEY),
];

pub static CLEAR_BUTTON: [(&str, &str); 7] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_108pc51",
        "j_id_jsp_635818149_109pc51",
    ),
    (
        "workspaceSubView:workspaceForm",
        "workspaceSubView:workspaceForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_54pc51",
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_54pc51",
    ),
    (
        "ajaxSingle",
        "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_54pc51",
    ),
];

pub static ORG_FILTER: [(&str, &str); 11] = [
    ("AJAXREQUEST", "j_id_jsp_659141934_0"),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_5pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_12pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_15pc22",
        "",
    ),
    (ORG_FILTER_BY_ID_KEY, ""),
    (
        "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_24pc22",
        "",
    ),
    (
        "orgSelectSubView:modalOrgSelectorForm",
        "orgSelectSubView:modalOrgSelectorForm",
    ),
    ("autoScroll", ""),
    ("javax.faces.ViewState", "j_id1"),
    (ORG_MODAL_FILTER_KEY, ORG_MODAL_FILTER_KEY),
    (AJAX_EVENTS_COUNT_KEY, "1"),
];

pub static CLICK_SEARCH_BOTTOM_NUMBER: [(&str, &str); 8] =[

        ("AJAXREQUEST", "j_id_jsp_659141934_0"),
        (
            "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_108pc51",
            "j_id_jsp_635818149_109pc51",
        ),
        (
            "workspaceSubView:workspaceForm",
            "workspaceSubView:workspaceForm",
        ),
        ("autoScroll", ""),
        ("javax.faces.ViewState", "j_id1"),
        (
            BOTTOM_NUMBER_KEY,
            "",
        ),
        (
            "ajaxSingle",
            "workspaceSubView:workspaceForm:workspacePageSubView:clientListTable:j_id_jsp_635818149_104pc51",
        ),
        ("AJAX:EVENTS_COUNT", "1"),
];

pub static CLICK_ORG_PAGE_KEY: &str =
    "orgSelectSubView:modalOrgSelectorForm:modalOrgSelectorOrgTable:j_id_jsp_685543358_39pc22";

pub static SUBMIT_SEARCH_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_53pc51";

pub static OPEN_ORG_SEARCH_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_6pc51";

pub static ORG_FILTER_BY_ID_KEY: &str =
    "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_18pc22";

pub static ORG_MODAL_FILTER_KEY: &str =
    "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_19pc22";

pub static FIRST_TABLE_ROW_KEY: &str =
    "orgSelectSubView:modalOrgSelectorForm:modalOrgSelectorOrgTable:0:j_id_jsp_685543358_32pc22";

pub static SUBMIT_SELECTED_ROW: &str =
    "orgSelectSubView:modalOrgSelectorForm:j_id_jsp_685543358_43pc22";

pub static NEXT_SEARCH_PAGE_KEY: &str = "workspaceSubView:workspaceForm:workspacePageSubView:clientListTable:j_id_jsp_635818149_104pc51";

pub static AJAX_EVENTS_COUNT_KEY: &str = "AJAX:EVENTS_COUNT";

pub static SEARCH_ID_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_12pc51";

pub static LAST_NAME_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_26pc51";

pub static NAME_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_30pc51";

pub static SURNAME_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_34pc51";

pub static SHOW_DELETED_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:showDeletedClients";

pub static CARDS_KEY: &str =
    "workspaceSubView:workspaceForm:workspacePageSubView:j_id_jsp_635818149_43pc51";

pub static BOTTOM_NUMBER_KEY: &str = "workspaceSubView:workspaceForm:workspacePageSubView:clientListTable:j_id_jsp_635818149_104pc51";

//pub static

pub static LIST_UNDO: [(&str, &str); 369] = [
    ("AJAXREQUEST",	"j_id_jsp_659141934_0"),
    ("mainMenuSubView:mainMenuForm:mainMenuselectedItemName",	"showClientListMenuItem"),
    ("panelMenuStatemainMenuSubView:mainMenuForm:orgGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:orgGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showOrgListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createOrgMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:settingsMenuGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settingsMenuGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settingsListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settingsCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:questionariesMenuGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:questionariesMenuGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:questionaryListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:questionaryLoadMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientAllocationRulesItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:distributionRulesMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:orgListLoaderMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:contragentGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contragentGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showContragentListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createContragentMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:ccAccountGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ccAccountGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ccAccountListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ccAccountCreateMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ccAccountFileLoadMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:posGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:posGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:posListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:posCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:settlementGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settlementGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settlementListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:settlementCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:addPaymentGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:addPaymentGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:addPaymentListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:addPaymentCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:contractGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contractGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contractListPageMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createContractMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:orgOfContractsReportPageMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:caOpsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:caOpsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:caReconcileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:caPaymentStatsMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:clientGroupMenu",	"opened"),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showClientListMenuItem",	"mainMenuSubView:mainMenuForm:showClientListMenuItem"),
    ("panelMenuStatemainMenuSubView:mainMenuForm:selectedClientGroupMenu",	"closed"),
    ("panelMenuActionmainMenuSubView:mainMenuForm:selectedClientGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:viewClientMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:editClientMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:viewClientOperationsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createClientMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadClientFromFileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadClientUpdateFromFileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contractBuildMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientLimitBatchEditMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientSmsListMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:clientOpsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientOpsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientBalanceTransferMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientRefundMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientSubAccountTransferMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:visitorDogmGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:visitorDogmGroupMenu",""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showVisitorDogmListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createVisitorDogmListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadVisitorFromFileMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:visitorDogmCardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:visitorDogmCardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showVisitorDogmCardListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createVisitorDogmCardListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:visitorDogmHistoryReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:cardGroupMenu",	"opened"),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showCardListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:selectedCardGroupMenu",	"opened"),
    ("panelMenuActionmainMenuSubView:mainMenuForm:selectedCardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:viewCardMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:editCardMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:viewCardOperationsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createCardMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadCardFromFileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadNewCardFromFileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cardExpireBatchEditMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:cardSignsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cardSignsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showCardSignListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cardSignListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:commodityAccountingGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:commodityAccountingGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:configurationProviderGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:configurationProviderGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:goodGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:goodsGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodsGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:listGoodGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createGoodGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:basicGoodGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:basicGoodGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:listBasicGoodMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createBasicGoodMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadingElementsOfBasicGoodsMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:productGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:productGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:productGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:productGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:listProductGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createProductGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:productListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:productCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:technologicalMapGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:technologicalMapGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:technologicalMapGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:technologicalMapGroupsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:listTechnologicalMapGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createTechnologicalMapGroupsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:listTechnologicalMapMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createTechnologicalMapMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:configurationProviderListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:configurationProviderCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:documentsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:documentsGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:wayBillGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:wayBillGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:wayBillListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:actOfInventorizationListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:actOfWayBillDifferencePositionListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:tradeMaterialGoodListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:serviceGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:serviceGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:removeOrderMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:logTestMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:buildSignKeysMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:supportEmailMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:fullSyncRequestItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:usePlanOrdersRequestItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:repositoryReportsRenameMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:loadRegistryFromFileMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:migrantsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:otherActionsMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:nsiGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiGroup",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:nsiGroupContingent",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiGroupContingent",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiPupilCatalogFind",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgRegistrySync",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgRegistrySyncOverview",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:photoRegistryItemMSK",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:nsiGroupOrg",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiGroupOrg",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgCatalogFind",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgsRegistrySync",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgsRegistrySyncSettings",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgsRegistryStat",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:nsiGroupEmployee",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiGroupEmployee",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:nsiOrgRegistryEmployeeSync",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:uosGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:uosGroup",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:uosSendBlock",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:uosStopList",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:autorecharge",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:autorecharge",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:groupControlSubscriptions",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:benefit",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:benefit",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:groupControlBenefits",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cancelBenefits",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:infoMessageGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:infoMessageGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:infoMessageList",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:infoMessageCreate",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:empInfo",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:syncStats",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:serviceRNIP",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:monitoringGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:monitoringGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:syncMonitorItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:dashboardMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:syncReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:statusSyncReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ordersMonitoringMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:persistanceCacheItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:reportOnlineGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportOnlineGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:complexGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:complexGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:allComplexReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:freeComplexReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:payComplexReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:discountsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:discountsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:allOrgsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:orgDiscountsReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:goodRequestsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodRequestsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:goodRequestNewReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:detailedGoodRequestReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:preordersMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:electronicReconciliationStatisticsReportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:electronicReconciliationStatisticsReportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:taloonApprovalVerificationMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:electronicReconciliationStatisticsMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:budgetReportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:budgetReportGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:registerStampGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampNewReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:registerStampElectronicCollationGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampElectronicCollationGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampNewElectronicCollationReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampElectronicCollationReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:feedingAndVisitSReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:deliveredServicesReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:deliveredServicesElectronicCollationReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:referReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:paidFoodGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:paidFoodGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampPaidReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:feedingSettingsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:feedingSettingsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:feedingSettingsListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showFeedingSettingCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:subscriptionFeedingGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:subscriptionFeedingGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:registerStampSubscriptionFeedingReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:acceptanceActGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:acceptanceActGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:acceptanceOfCompletedWorksActMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:paymentReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:paymentReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contragentCompletionReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:contragentPaymentReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientPaymentsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:currentPositionReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:payStatsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:regularPaymentsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:paymentTotalsReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:activityReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:activityReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:activeClientsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:commonStatsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:activeDiscountClientsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:zeroTransactionsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:specialDatesReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:migrantsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:monitoringOfMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientTransactionsReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:clientsReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientsReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:сlientBalanceByDayReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:сlientBalanceByOrgReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:balanceLeavingReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:informReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:informReportsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:SentSmsReportPageMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:OrgSmsDeliveryReportPageMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:OrgSmsStatsReportPageMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:SmsAddressesReportPageMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:statisticDifferencesGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:statisticDifferencesGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:statisticsDiscrepanciesOnOrdersAndAttendanceReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:requestsAndOrdersReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:detailedDeviationsWithoutCorpsNewReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:financialControlMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:financialControlMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:latePaymentReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:latePaymentDetailedReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:salesReportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:salesReportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:dailySalesByGroupsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:salesReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:aggregateCostsAndSalesReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:totalSalesReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ordersByManufacturerReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:generateOrgOrderReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:basicBasketReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:paymentsBetweenContragentsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:consolidatedSellingReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:cardGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:cardGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:typesOfCardReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:interactiveCardDataMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:issuedCardsReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:passReportsGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:passReportsGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:detailedEnterEventReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:autoEnterEventReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:enterEventJournalReportPageMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:enterEventReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:helpdeskGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:helpdeskGroupPageMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:helpdeskMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:totalServicesReportPage",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:clientsBenefitsReportMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:transactionsReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:reportRepositoryGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportRepositoryGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportRepositoryListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:optionGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:optionGroupMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:optionsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:optionsGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showOptionMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showMessageConfigureMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showConfigurationMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showLicInfoMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showIstkKioskOptionsMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showexternalSystemsItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:eventNotificationGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:eventNotificationGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:eventNotificationRuleListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:eventNotificationRuleCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:employeesGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:employeesGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showEmployeeListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createEmployeeListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:employeesCardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:employeesCardGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showEmployeeCardListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:createEmployeeCardListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:employeeHistoryReportMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:benefitsOptionsMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:benefitsOptionsMenu",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:categoryOrgGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryOrgGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showCategoryOrgsListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showCategoryOrgsCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:categoryGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:categoryDSZNGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryDSZNGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryDSZNListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:categoryCreateDSZNMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:ruleGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ruleGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ruleListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:ruleCreateMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:complexRoleEditMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:reportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showReportTemplateManagerMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:reportJobGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportJobGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportJobListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportJobCreateMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportQuartzJobsListMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:reportRuleGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportRuleGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportRuleListMenuItem",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:reportRuleCreateMenuItem",	""),
    ("panelMenuStatemainMenuSubView:mainMenuForm:infoGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:infoGroupMenu",	""),
    ("panelMenuActionmainMenuSubView:mainMenuForm:showCryptoInfo",	""),
    ("mainMenuSubView:mainMenuForm",	"mainMenuSubView:mainMenuForm"),
    ("autoScroll",	""),
    ("javax.faces.ViewState",	"j_id1"),
    ("mainMenuSubView:mainMenuForm:showClientListMenuItem",	"mainMenuSubView:mainMenuForm:showClientListMenuItem"),
];
